### ISSUE TITLE
[Feature] - Add User's number contributions in the last year from github

### ISSUE THREAD

**Issue by MrSlimCoder** [NomanGul/octocat-day#36]
Hello contributors i'm in love with project i'm looking forward to add a new feature which get user's number of contributions of in the last year see this [link](https://github.com/users/viveksharmaui/contributions) . 
I did not find any github api if you find then share , I'm also looking forward to scrape web and get user contributions in the last year .

**Comment by NomanGul** [comment]
@viveksharmaui This is out of this project scope... What do you think?

**Comment by MrSlimCoder** [comment]
I think this feature is important also we should work and add new features into it . i mean the current project idea is very basic .
