### ISSUE TITLE
Is there a hosted version of the application somewhere?

### ISSUE THREAD

**Issue by russelljjarvis** [NomanGul/octocat-day#54]
The URL octocatday resolves then redirects to dodgy commercial sites.

https://www.octocatday.com/

For example:
https://protonvpn.com/free-vpn?url_id=0&utm_campaign=ww-all-2a-vpn-gro_aff-partners_program&utm_medium=link&utm_source=aid-tune-1942&utm_content=6

**Comment by NomanGul** [comment]
sorry, It seems like the domain is expired. I'll deploy it on GitHub pages.

**Comment by russelljjarvis** [comment]
Thanks  @NomanGul! I think the app sounds cool, so I am glad you can do that!

**Comment by AvirukBasak** [comment]
@NomanGul It's been a while.

https://octocatday.com - ERR_SSL_PROTOCOL_ERROR
http://octocatday.com - Redirects to http://ww7.octocatday.com/

**Comment by russelljjarvis** [comment]
I think that this hosted app can get your GH birthday too: https://github-readme-streak-stats.herokuapp.com 

For now, it is what I use. Examples:


![GitHub Streak](https://github-readme-streak-stats.herokuapp.com/?user=NomanGul&theme=dark)

![GitHub Streak](https://github-readme-streak-stats.herokuapp.com/?user=AvirukBasak&theme=dark)

**Comment by NomanGul** [comment]
new domain => https://nomangul.github.io/octocat-day/
